name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
      url: https://cssc.utm.utoronto.ca/
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: compose build
        run: docker compose build

      - name: compose up
        run: docker compose up -d

      - name: cleanup
        run: |
          docker image prune -f
          docker builder prune -f 
